const KEY='fms-pkr1m-v1',money=n=>'PKR '+Number(n||0).toLocaleString('en-PK'),pct=n=>Math.round((Number(n)||0)*100)+'%';
const seed={income:[['CS Technologies',0,0],['Stellar Career College',0,0],['Fix My Search Retainers',0,750000],['Local Clients',0,120000],['Daily Dose',0,150000],['Al Haider',0,100000],['Digital Products',0,100000]],pipeline:[['International Prospect','Fix My Search Retainer','Prospect',250000,10,'Personalize outreach'],['Daily Dose','Bakery Growth Pilot','Proposal',150000,50,'Present pilot proposal'],['Al Haider Water Boring','Local Growth System','Qualified',100000,70,'Launch lead campaign']],projects:[['Fix My Search','Launch portfolio and win three retainers','In Progress',750000],['Daily Dose','Run a tracked bakery growth pilot','In Progress',150000],['Al Haider Water Boring','Launch local lead-generation system','In Progress',100000],['Stellar Career College','Complete 90-day marketing system','Active',0],['CS Technologies','Organize teaching and course system','Active',0],['Digital Product','Validate and launch one product','Not Started',100000]],actions:[['Send 25 personalized outreach messages','Fix My Search',25,0,'Not Started'],['Book five qualified sales calls','Fix My Search',5,0,'Not Started'],['Present the tracked pilot proposal','Daily Dose',1,0,'In Progress'],['Launch the local lead campaign','Al Haider',1,0,'In Progress']]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(seed);const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()};
document.getElementById('today').textContent=new Intl.DateTimeFormat('en-PK',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('aside nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}document.addEventListener('click',e=>{const id=e.target.closest('[data-view]')?.dataset.view;if(id)show(id)});
function render(){const total=state.income.reduce((s,x)=>s+Number(x[1]),0),target=1e6,gap=Math.max(0,target-total),progress=Math.min(1,total/target);actualKpi.textContent=money(total);gapKpi.textContent=money(gap);progressKpi.textContent=pct(progress);progressBar.style.width=pct(progress);actualSignal.textContent=total?'Revenue recorded':'Enter income below';
 revenueBars.innerHTML=state.income.map(x=>`<div class="bar-row"><span>${x[0]}</span><div class="bar"><i style="width:${Math.min(100,Number(x[1])/Math.max(1,Number(x[2]))*100)}%"></i></div><span>${money(x[1])}</span></div>`).join('');
 const weighted=state.pipeline.reduce((s,x)=>s+Number(x[3])*Number(x[4])/100,0);weightedPipeline.textContent=money(weighted);activeLeads.textContent=state.pipeline.filter(x=>!['Won','Lost'].includes(x[2])).length;wonLeads.textContent=state.pipeline.filter(x=>x[2]==='Won').length;coverage.textContent=pct(weighted/target);coverageBar.style.width=Math.min(100,weighted/target*100)+'%';
 priorityActions.innerHTML=state.actions.slice(0,4).map((x,i)=>`<div class="priority-item"><span>${i+1}</span><div><b>${x[0]}</b><small>${x[1]} · ${x[3]}/${x[2]} complete</small></div><i class="status">${x[4]}</i></div>`).join('')||'<p>No actions yet.</p>';projectSummary.innerHTML=state.projects.slice(0,5).map(x=>`<div class="summary-item"><div></div><div><b>${x[0]}</b><small>${x[1]}</small></div><i class="status">${x[2]}</i></div>`).join('');
 incomeRows.innerHTML=state.income.map((x,i)=>`<tr><td><input data-t="income" data-i="${i}" data-c="0" value="${x[0]}"></td><td><input type="number" data-t="income" data-i="${i}" data-c="1" value="${x[1]}"></td><td><input type="number" data-t="income" data-i="${i}" data-c="2" value="${x[2]}"></td><td>${money(Math.max(0,x[2]-x[1]))}</td><td>${pct(x[2]?x[1]/x[2]:0)}</td><td><button class="delete" data-del="income" data-i="${i}">×</button></td></tr>`).join('');
 pipelineRows.innerHTML=state.pipeline.map((x,i)=>`<tr><td><input data-t="pipeline" data-i="${i}" data-c="0" value="${x[0]}"></td><td><input data-t="pipeline" data-i="${i}" data-c="1" value="${x[1]}"></td><td><select data-t="pipeline" data-i="${i}" data-c="2">${['Prospect','Contacted','Qualified','Proposal','Negotiation','Won','Lost'].map(o=>`<option ${o===x[2]?'selected':''}>${o}</option>`).join('')}</select></td><td><input type="number" data-t="pipeline" data-i="${i}" data-c="3" value="${x[3]}"></td><td><input type="number" data-t="pipeline" data-i="${i}" data-c="4" value="${x[4]}"></td><td>${money(x[3]*x[4]/100)}</td><td><input data-t="pipeline" data-i="${i}" data-c="5" value="${x[5]}"></td><td><button class="delete" data-del="pipeline" data-i="${i}">×</button></td></tr>`).join('');
 projectCards.innerHTML=state.projects.map((x,i)=>`<article class="project-card"><header><span class="status">${x[2]}</span><button class="delete" data-del="projects" data-i="${i}">×</button></header><h3>${x[0]}</h3><p>${x[1]}</p><footer><span>Monthly goal</span><b>${money(x[3])}</b></footer></article>`).join('');
 actionList.innerHTML=state.actions.map((x,i)=>`<article class="action-row"><span>${i+1}</span><div><h3>${x[0]}</h3><small>${x[1]}</small></div><div class="action-progress"><b>${x[3]} / ${x[2]}</b><small>completed</small></div><span class="status action-status">${x[4]}</span><button class="delete" data-del="actions" data-i="${i}">×</button></article>`).join('')}
document.addEventListener('change',e=>{const el=e.target;if(!el.dataset.t)return;state[el.dataset.t][+el.dataset.i][+el.dataset.c]=el.type==='number'?Number(el.value):el.value;save()});document.addEventListener('click',e=>{const b=e.target.closest('[data-del]');if(b){state[b.dataset.del].splice(+b.dataset.i,1);save()}});
const configs={addIncome:['INCOME','Add income source',[['Source','text'],['Actual PKR','number'],['Monthly goal','number']]],addLead:['PIPELINE','Add opportunity',[['Lead / company','text'],['Offer','text'],['Potential PKR','number'],['Probability %','number'],['Next action','text']]],addProject:['PROJECT','Add project',[['Project','text'],['Outcome','text'],['Monthly goal PKR','number']]],addAction:['WEEKLY ACTION','Add revenue action',[['Action','text'],['Project','text'],['Target count','number']]]};let current=null;Object.keys(configs).forEach(id=>document.getElementById(id).onclick=()=>openModal(id));function openModal(id){current=id;const c=configs[id];modalEyebrow.textContent=c[0];modalTitle.textContent=c[1];fields.innerHTML=c[2].map((f,i)=>`<div class="field"><label>${f[0]}</label><input name="f${i}" type="${f[1]}" required></div>`).join('');modal.showModal()}
form.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return; e.preventDefault();const v=[...fields.querySelectorAll('input')].map(x=>x.type==='number'?Number(x.value):x.value);if(current==='addIncome')state.income.push(v);if(current==='addLead')state.pipeline.push([v[0],v[1],'Prospect',v[2],v[3],v[4]]);if(current==='addProject')state.projects.push([v[0],v[1],'Not Started',v[2]]);if(current==='addAction')state.actions.push([v[0],v[1],v[2],0,'Not Started']);modal.close();save()});reset.onclick=()=>{if(confirm('Replace your browser data with the original dashboard template?')){state=structuredClone(seed);save()}};render();
